import { useState } from 'react'
import { FiCheckCircle, FiTool } from 'react-icons/fi'
import { toast } from 'react-toastify'
import { useAuth } from '../context/AuthContext'
import { createFacilityRequest, getFacilityCategories, getFacilityRequests } from '../services/facilityService'
import EmptyState from '../components/common/EmptyState'

/** Facilities and functional handling request page. */
export default function FacilitiesPage() { const { user } = useAuth(); const [requests, setRequests] = useState(() => getFacilityRequests(user)); const [form, setForm] = useState({ category: 'IT support', title: '', description: '', priority: 'normal' }); function submit(event) { event.preventDefault(); if (!form.title || !form.description) { toast.error('Complete the request title and description.'); return }; createFacilityRequest(user, form); setRequests(getFacilityRequests(user)); setForm({ ...form, title: '', description: '' }); toast.success('Service request created.') } return <div className="space-y-6"><div><p className="text-sm font-medium text-blue-600">Employee services</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Facilities handling</h1><p className="mt-2 text-slate-500">Request support for workplace, IT, maintenance, and events.</p></div><section className="max-w-2xl rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><form className="space-y-4" onSubmit={submit}><label className="block"><span className="label">Category</span><select className="field bg-white" name="category" onChange={(event) => setForm({ ...form, category: event.target.value })} value={form.category}>{getFacilityCategories().map((category) => <option key={category}>{category}</option>)}</select></label><label className="block"><span className="label">Request title</span><input className="field" onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="What do you need?" value={form.title} /></label><label className="block"><span className="label">Description</span><textarea className="field min-h-28" onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Describe the issue or requirement" value={form.description} /></label><button className="flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white" type="submit"><FiTool /> Submit request</button></form></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">My service requests</h2>{requests.length ? requests.map((request) => <div className="flex justify-between border-b border-slate-100 py-3 text-sm" key={request.id}><span><strong>{request.title}</strong><br /><span className="text-slate-500">{request.category}</span></span><span className="flex items-center gap-1 capitalize text-blue-600"><FiCheckCircle /> {request.status}</span></div>) : <EmptyState message="No service requests yet." icon={FiTool} />}</section></div> }
