import { useState } from 'react'
import { FiCheck, FiPlus, FiShoppingBag } from 'react-icons/fi'
import { toast } from 'react-toastify'
import { useAuth } from '../context/AuthContext'
import { createFoodOrder, getFoodOrders, getMenu } from '../services/foodCourtService'
import EmptyState from '../components/common/EmptyState'

/** QR food court ordering page. */
export default function FoodCourtPage() {
  const { user } = useAuth(); const menu = getMenu(); const [cart, setCart] = useState([]); const [orders, setOrders] = useState(() => getFoodOrders(user))
  function add(item) { setCart((current) => { const found = current.find((entry) => entry.id === item.id); return found ? current.map((entry) => entry.id === item.id ? { ...entry, quantity: entry.quantity + 1 } : entry) : [...current, { ...item, quantity: 1 }] }) }
  function order() { if (!cart.length) { toast.error('Add an item first.'); return }; createFoodOrder(user, cart); setCart([]); setOrders(getFoodOrders(user)); toast.success('Food order sent to the food court.') }
  return <Page title="Food court" subtitle="Scan, order, and collect your meal without waiting in line."><div className="grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><section className="grid gap-4 sm:grid-cols-2">{menu.map((item) => <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" key={item.id}><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">{item.category}</span><h2 className="mt-4 font-bold text-slate-900">{item.name}</h2><p className="mt-2 text-lg font-bold text-slate-900">LKR {item.price.toLocaleString()}</p><button className="mt-4 flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white" onClick={() => add(item)} type="button"><FiPlus /> Add to order</button></article>)}</section><aside className="h-fit rounded-xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2"><FiShoppingBag /><h2 className="font-bold">Your QR order</h2></div>{cart.length ? <div className="mt-5 space-y-3">{cart.map((item) => <div className="flex justify-between text-sm" key={item.id}><span>{item.name} x{item.quantity}</span><span>LKR {(item.price * item.quantity).toLocaleString()}</span></div>)}<button className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-400 px-4 py-3 font-bold text-slate-950" onClick={order} type="button"><FiCheck /> Confirm order</button></div> : <p className="mt-5 text-sm text-slate-400">Your order is empty.</p>}</aside></div><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Recent orders</h2>{orders.length ? <div className="mt-4 divide-y divide-slate-100">{orders.slice(0, 5).map((order) => <p className="flex justify-between py-3 text-sm" key={order.id}><span>{order.items.map((item) => item.name).join(', ')}</span><span className="capitalize text-blue-600">{order.status}</span></p>)}</div> : <EmptyState message="No food orders yet." icon={FiShoppingBag} />}</section></Page>
}
function Page({ title, subtitle, children }) { return <div className="space-y-6"><div><p className="text-sm font-medium text-blue-600">Employee services</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{title}</h1><p className="mt-2 text-slate-500">{subtitle}</p></div>{children}</div> }
