import { useState } from 'react'
import { FiCheck, FiMapPin } from 'react-icons/fi'
import { toast } from 'react-toastify'
import { useAuth } from '../context/AuthContext'
import { bookTransport, getRoutes, getTransportBookings } from '../services/transportService'
import EmptyState from '../components/common/EmptyState'

/** Employee transport reservation page. */
export default function TransportPage() { const { user } = useAuth(); const [bookings, setBookings] = useState(() => getTransportBookings(user)); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); function book(routeId) { bookTransport(user, routeId, date); setBookings(getTransportBookings(user)); toast.success('Transport seat requested.') } return <div className="space-y-6"><Header title="Transport management" subtitle="Reserve a company shuttle for your commute." /><div className="flex max-w-xs items-end gap-3"><label className="block flex-1"><span className="label">Travel date</span><input className="field" onChange={(event) => setDate(event.target.value)} type="date" value={date} /></label></div><section className="grid gap-4 md:grid-cols-3">{getRoutes().map((route) => <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" key={route.id}><FiMapPin className="text-blue-600" size={24} /><h2 className="mt-4 font-bold text-slate-900">{route.name}</h2><p className="mt-2 text-sm text-slate-500">Departure {route.time} · {route.driver}</p><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white" onClick={() => book(route.id)} type="button"><FiCheck /> Reserve seat</button></article>)}</section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">My reservations</h2>{bookings.length ? <div className="mt-4 divide-y divide-slate-100">{bookings.map((booking) => <p className="flex justify-between py-3 text-sm" key={booking.id}><span>{booking.passenger} · {booking.date}</span><span className="capitalize text-blue-600">{booking.status}</span></p>)}</div> : <EmptyState message="No transport reservations yet." icon={FiMapPin} />}</section></div> }
function Header({ title, subtitle }) { return <div><p className="text-sm font-medium text-blue-600">Employee services</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{title}</h1><p className="mt-2 text-slate-500">{subtitle}</p></div> }
