import { useState } from 'react'
import { FiHome } from 'react-icons/fi'
import { toast } from 'react-toastify'
import { useAuth } from '../context/AuthContext'
import { getAccommodationRequests, getRooms, requestAccommodation } from '../services/accommodationService'
import EmptyState from '../components/common/EmptyState'

/** Accommodation booking request page. */
export default function AccommodationPage() { const { user } = useAuth(); const [requests, setRequests] = useState(() => getAccommodationRequests(user)); const [dates, setDates] = useState({ checkIn: '', checkOut: '' }); function request(roomId) { if (!dates.checkIn || !dates.checkOut) { toast.error('Choose check-in and check-out dates.'); return }; requestAccommodation(user, { roomId, ...dates }); setRequests(getAccommodationRequests(user)); toast.success('Accommodation request submitted.') } return <div className="space-y-6"><div><p className="text-sm font-medium text-blue-600">Employee services</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Accommodation</h1><p className="mt-2 text-slate-500">Request comfortable stays for business travel and events.</p></div><div className="grid max-w-lg gap-4 sm:grid-cols-2"><label className="block"><span className="label">Check in</span><input className="field" onChange={(event) => setDates({ ...dates, checkIn: event.target.value })} type="date" value={dates.checkIn} /></label><label className="block"><span className="label">Check out</span><input className="field" onChange={(event) => setDates({ ...dates, checkOut: event.target.value })} type="date" value={dates.checkOut} /></label></div><section className="grid gap-4 md:grid-cols-3">{getRooms().map((room) => <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" key={room.id}><FiHome className="text-blue-600" size={24} /><h2 className="mt-4 font-bold text-slate-900">{room.name}</h2><p className="mt-2 text-sm text-slate-500">{room.type} · Sleeps {room.capacity}</p><p className="mt-3 font-bold text-slate-900">LKR {room.nightlyRate.toLocaleString()} / night</p><button className="mt-5 w-full rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white" onClick={() => request(room.id)} type="button">Request stay</button></article>)}</section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">My requests</h2>{requests.length ? requests.map((request) => <p className="flex justify-between border-b border-slate-100 py-3 text-sm" key={request.id}><span>{request.checkIn} to {request.checkOut}</span><span className="capitalize text-blue-600">{request.status}</span></p>) : <EmptyState message="No accommodation requests yet." icon={FiHome} />}</section></div> }
