import { useMemo, useState } from 'react'
import { FiDownload, FiFileText } from 'react-icons/fi'
import { Navigate } from 'react-router-dom'
import { getAuditLogs } from '../utils/auditLogger'
import { useAuth } from '../context/AuthContext'
import EmptyState from '../components/common/EmptyState'
import { toast } from 'react-toastify'

/** Render the admin-only audit log table and filters. @returns {JSX.Element} Audit logs page. */
export default function AuditLogsPage() {
  const { user } = useAuth()
  const [filters, setFilters] = useState({ user: '', action: '', startDate: '', endDate: '' })
  const logs = useMemo(() => getAuditLogs(filters), [filters])
  if (user?.role !== 'admin') return <Navigate replace to="/dashboard" />
  const actionTypes = [...new Set(getAuditLogs().map((log) => log.action))]

  function updateFilter(event) { setFilters((current) => ({ ...current, [event.target.name]: event.target.value })) }
  function exportCsv() { const header = 'Timestamp,User,Action,Details'; const body = logs.map((log) => [log.timestamp, log.user, log.action, log.details].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const blob = new Blob([[header, body].join('\n')], { type: 'text/csv;charset=utf-8;' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'attendease-audit-logs.csv'; link.click(); URL.revokeObjectURL(url); toast.success('Audit log CSV exported.') }

  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-blue-600">Governance</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Audit logs</h1><p className="mt-2 text-slate-500">Review important actions across your workspace.</p></div><button className="flex items-center gap-2 self-start rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700 sm:self-auto" onClick={exportCsv} type="button"><FiDownload /> Export CSV</button></div><section className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm lg:flex-row lg:items-end"><label className="block flex-1"><span className="label">User</span><input className="field" name="user" onChange={updateFilter} placeholder="Search user" value={filters.user} /></label><label className="block"><span className="label">Action type</span><select className="field bg-white" name="action" onChange={updateFilter} value={filters.action}><option value="">All actions</option>{actionTypes.map((action) => <option key={action}>{action}</option>)}</select></label><label className="block"><span className="label">From</span><input className="field" name="startDate" onChange={updateFilter} type="date" value={filters.startDate} /></label><label className="block"><span className="label">To</span><input className="field" name="endDate" onChange={updateFilter} type="date" value={filters.endDate} /></label><button className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50" onClick={() => setFilters({ user: '', action: '', startDate: '', endDate: '' })} type="button">Reset</button></section><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-4"><FiFileText className="text-blue-600" /><p className="font-semibold text-slate-900">{logs.length} audit entries</p></div><div className="overflow-x-auto"><table className="min-w-[800px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Timestamp', 'User', 'Action', 'Details'].map((heading) => <th className="px-5 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{logs.map((log) => <tr key={log.id}><td className="whitespace-nowrap px-5 py-4 text-slate-500">{new Date(log.timestamp).toLocaleString()}</td><td className="px-5 py-4 font-medium text-slate-800">{log.user}</td><td className="px-5 py-4"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{log.action}</span></td><td className="max-w-lg px-5 py-4 text-slate-600">{log.details}</td></tr>)}</tbody></table>{!logs.length && <EmptyState message="No audit records match these filters." icon={FiFileText} />}</div></section></div>
}
